/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Children: typeof import('./src/components/comment/Children.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommentRow: typeof import('./src/components/comment/CommentRow.vue')['default']
    CreateFavouriteCard: typeof import('./src/components/CreateFavouriteCard.vue')['default']
    DcAuthorIcon: typeof import('@delta-comic/ui')['DcAuthorIcon']
    DcAwait: typeof import('@delta-comic/ui')['DcAwait']
    DcContent: typeof import('@delta-comic/ui')['DcContent']
    DcImage: typeof import('@delta-comic/ui')['DcImage']
    DcImagedIcon: typeof import('@delta-comic/ui')['DcImagedIcon']
    DcList: typeof import('@delta-comic/ui')['DcList']
    DcPopup: typeof import('@delta-comic/ui')['DcPopup']
    DcText: typeof import('@delta-comic/ui')['DcText']
    DcToggleIcon: typeof import('@delta-comic/ui')['DcToggleIcon']
    DcVar: typeof import('@delta-comic/ui')['DcVar']
    FavouriteSelect: typeof import('./src/components/FavouriteSelect.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    PreviewUser: typeof import('./src/components/user/PreviewUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sender: typeof import('./src/components/comment/Sender.vue')['default']
    ShareButton: typeof import('./src/components/ShareButton.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopover: typeof import('vant/es')['Popover']
    VanRow: typeof import('vant/es')['Row']
    VanSlider: typeof import('vant/es')['Slider']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
