packages:
  - packages/*

catalogMode: strict
cleanupUnusedCatalogs: true

allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  '@commitlint/cli': ^21.2.2
  '@commitlint/config-conventional': ^21.2.2
  '@delta-comic/db': '3.0.0-next.13'
  '@delta-comic/model': '3.0.0-next.13'
  '@delta-comic/plugin': '3.0.0-next.13'
  '@delta-comic/ui': '3.0.0-next.13'
  '@delta-comic/utils': '3.0.0-next.13'
  '@pinia/colada': ^1.4.2
  '@semantic-release/commit-analyzer': ^13.0.1
  '@semantic-release/github': ^12.0.9
  '@semantic-release/release-notes-generator': ^14.1.1
  '@tailwindcss/vite': ^4.3.3
  '@types/node': 25.9.0
  '@vicons/antd': ^0.13.0
  '@vicons/material': ^0.13.0
  '@vitejs/plugin-vue': ^6.0.8
  '@vueuse/core': ^14.4.0
  '@vitest/coverage-v8': 4.1.10
  artplayer: ^5.4.0
  browserslist: ^4.28.8
  commitlint-plugin-cspell: ^0.9.4
  cspell: ^10.0.1
  dayjs: ^2.0.0-alpha.4
  dompurify: ^3.4.13
  es-toolkit: ^1.50.0
  happy-dom: ^20.11.1
  hls.js: ^1.7.0-rc.3
  jszip: ^3.10.1
  lightningcss: ^1.33.0
  naive-ui: ^2.44.1
  oxlint-tsgolint: ^7.0.2001
  semantic-release: ^25.0.8
  swiper: ^14.1.0
  tailwindcss: ^4.3.3
  typescript: npm:typescript-native-bridge@6.0.3-bridge.8.tsgo.7.0.2
  unplugin-vue-components: 32.1.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: ^0.2.9
  vitest: 4.1.10
  vue: ^3.6.0-rc.4
  vue-component-type-helpers: ^3.3.9
  vue-router: ^5.2.0
  vue-tsc: ^3.3.9
  rolldown-plugin-dts: ^0.28.2
overrides:
  typescript: npm:typescript-native-bridge@6.0.3-bridge.8.tsgo.7.0.2
  '@c4312/blake3-internal': ^3.0.0
  brace-expansion@1.1.15: 1.1.18
  fast-uri@3.1.3: 3.1.5
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

minimumReleaseAgeExclude:
  - '@delta-comic/db@3.0.0-next.13'
  - '@delta-comic/downloader@3.0.0-next.13'
  - '@delta-comic/logger@3.0.0-next.13'
  - '@delta-comic/model@3.0.0-next.13'
  - '@delta-comic/plugin@3.0.0-next.13'
  - '@delta-comic/ui@3.0.0-next.13'
  - '@delta-comic/utils@3.0.0-next.13'
  - hls.js@1.7.0-rc.3
  - '@vue/compiler-core@3.6.0-rc.4'
  - '@vue/compiler-dom@3.6.0-rc.4'
  - '@vue/compiler-sfc@3.6.0-rc.4'
  - '@vue/compiler-ssr@3.6.0-rc.4'
  - '@vue/compiler-vapor@3.6.0-rc.4'
  - '@vue/reactivity@3.6.0-rc.4'
  - '@vue/runtime-core@3.6.0-rc.4'
  - '@vue/runtime-dom@3.6.0-rc.4'
  - '@vue/runtime-vapor@3.6.0-rc.4'
  - '@vue/server-renderer@3.6.0-rc.4'
  - '@vue/shared@3.6.0-rc.4'
  - vue@3.6.0-rc.4