name: 其他
description: 不符合其他的选择(请仔细思考!)
title: '[其他] <简易描述>'
body:
  - type: markdown
    attributes:
      value: |
        提交时请将上方标题中 `<>` 占位符替换为实际描述(不保留尖括号)。

  - type: input
    id: tag
    attributes:
      label: 版本信息
      description: 填写 Delta Comic 核心版本和基础布局插件版本
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 详细描述
    validations:
      required: true