/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonPopup: typeof import('./src/components/ButtonPopup.vue')['default']
    Children: typeof import('./src/components/comment/Children.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommentRow: typeof import('./src/components/comment/CommentRow.vue')['default']
    CreateFavouriteCard: typeof import('./src/components/CreateFavouriteCard.vue')['default']
    DcAwait: typeof import('@delta-comic/ui')['DcAwait']
    DcCellGroup: typeof import('@delta-comic/ui')['DcCellGroup']
    DcFormDate: typeof import('@delta-comic/ui')['DcFormDate']
    DcFormDateRange: typeof import('@delta-comic/ui')['DcFormDateRange']
    DcFormNumber: typeof import('@delta-comic/ui')['DcFormNumber']
    DcFormPairs: typeof import('@delta-comic/ui')['DcFormPairs']
    DcFormString: typeof import('@delta-comic/ui')['DcFormString']
    DcFormSwitch: typeof import('@delta-comic/ui')['DcFormSwitch']
    DcVar: typeof import('@delta-comic/ui')['DcVar']
    FavouriteSelect: typeof import('./src/components/FavouriteSelect.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NIcon: typeof import('naive-ui')['NIcon']
    NModal: typeof import('naive-ui')['NModal']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    PreviewUser: typeof import('./src/components/user/PreviewUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sender: typeof import('./src/components/comment/Sender.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    ShareButton: typeof import('./src/components/ShareButton.vue')['default']
  }
}
