/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonPopup: typeof import('./src/components/ButtonPopup.vue')['default']
    Children: typeof import('./src/components/comment/Children.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommentRow: typeof import('./src/components/comment/CommentRow.vue')['default']
    CreateFavouriteCard: typeof import('./src/components/CreateFavouriteCard.vue')['default']
    FavouriteSelect: typeof import('./src/components/FavouriteSelect.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    PreviewUser: typeof import('./src/components/user/PreviewUser.vue')['default']
    Sender: typeof import('./src/components/comment/Sender.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    ShareButton: typeof import('./src/components/ShareButton.vue')['default']
  }
}
